### ISSUE TITLE
Enhancement: Add property chromeDriverBinary to enable specification in wdio.conf.js

### ISSUE THREAD

**Issue by duderonomy** [atti187/wdio-chromedriver-service#21]
Hello

I am not sure how to use a self-prescribed `chromedriver` binary which may be required by a software development kit. 

I don't know how to specify a chromedriver binary of your choice in the local file system.  

Even if I were attempting to use the chromedriver in wdio-chromedriver-service that is supposed to work "out of the box", I am not sure I know how to make that work that either. I followed the instructions but unable to avoid: `Error: Couldn't initialise "wdio-chromedriver-service".` 

With the same wdioconf.js file (as the one that produces the output below) I can comment out one line: 
```services: ['chromedriver']```
then manually start the SDK-provided chromedriver, from another shell: `./bin/chromedriver --port=9515`, then run wdio. That works as expected. 

I would like to know how to do two things:
 - Specify the path to a special chromedriver binary that exists in my file system
 - Get the wdio-chromedriver-service to use the chromedriver included as a peer dependency

I read the other issues to try to find the answer. Particularly notable is #11. It was a surprise to hear @christian-bromann not imagine a reason to use a specific older version of software as opposed to the latest and current version. Maybe he is only thinking about things in the realm of being "out in front" of the latest browser changes and not the creation of test cases for legacy code. 

Thank you for writing this service. It is just the right functionality to encapsulate! I appreciate your foresight.

If any resulting code or documentation changes result from my question, then I will watch closely with intent of helping to support this package. 

And please let me know if the log is insufficient and does not give you everything you may need to help me.

```
$ DEBUG=true ./node_modules/.bin/wdio wdio.conf.js
2019-05-19T22:53:05.132Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "chromedriver"
2019-05-19T22:53:05.145Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-chromedriver-service".
Error: Cannot find module 'chromedriver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/wdio-chromedriver-service/build/launcher.js:10:44)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at safeRequire (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/utils/build/initialisePlugin.js:19:13)
    at initialisePlugin (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/utils/build/initialisePlugin.js:56:18)
    at initialiseServices (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/utils/build/initialiseServices.js:64:53)
    at Launcher.run (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/cli/build/launcher.js:70:52)
    at launch (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/cli/build/run.js:88:12)
    at run (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/cli/build/run.js:64:12)
    at Object.run (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/cli/build/index.js:45:20)
    at Object.<anonymous> (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/cli/bin/wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
2019-05-19T22:53:05.146Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-05-19T22:53:05.148Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js

RUNNING  0-0 in chrome - /test/specs/basic.js

Stdout:
[0-0] 2019-05-19T22:53:05.339Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-05-19T22:53:05.343Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "chromedriver"
[0-0] 2019-05-19T22:53:05.360Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2019-05-19T22:53:05.382Z INFO webdriver: [POST] http://127.0.0.1:9515/session
[0-0] 2019-05-19T22:53:05.382Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', chromeOptions: [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      chromeOptions:
       { binary:
          '../../desktop/sdk/osx32/chromium.app/Contents/MacOS/chromebrowser' } } }
[0-0] 2019-05-19T22:53:05.392Z INFO webdriver: Retrying 1/3
[0-0] 2019-05-19T22:53:05.392Z INFO webdriver: [POST] http://127.0.0.1:9515/session
[0-0] 2019-05-19T22:53:05.392Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', chromeOptions: [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      chromeOptions:
       { binary:
          '../../desktop/sdk/osx32/chromium.app/Contents/MacOS/chromebrowser' } } }
[0-0] 2019-05-19T22:53:05.393Z INFO webdriver: Retrying 2/3
[0-0] 2019-05-19T22:53:05.394Z INFO webdriver: [POST] http://127.0.0.1:9515/session
[0-0] 2019-05-19T22:53:05.394Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', chromeOptions: [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
Stdout:
[0-0] 2019-05-19T22:53:05.339Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-05-19T22:53:05.343Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "chromedriver"
[0-0] 2019-05-19T22:53:05.360Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2019-05-19T22:53:05.382Z INFO webdriver: [POST] http://127.0.0.1:9515/session
[0-0] 2019-05-19T22:53:05.382Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', chromeOptions: [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      chromeOptions:
       { binary:
          '../../desktop/sdk/osx32/chromium.app/Contents/MacOS/chromebrowser' } } }
[0-0] 2019-05-19T22:53:05.392Z INFO webdriver: Retrying 1/3
[0-0] 2019-05-19T22:53:05.392Z INFO webdriver: [POST] http://127.0.0.1:9515/session
[0-0] 2019-05-19T22:53:05.392Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', chromeOptions: [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      chromeOptions:
       { binary:
          '../../desktop/sdk/osx32/chromium.app/Contents/MacOS/chromebrowser' } } }
[0-0] 2019-05-19T22:53:05.393Z INFO webdriver: Retrying 2/3
[0-0] 2019-05-19T22:53:05.394Z INFO webdriver: [POST] http://127.0.0.1:9515/session
[0-0] 2019-05-19T22:53:05.394Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', chromeOptions: [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      chromeOptions:
       { binary:
          '../../desktop/sdk/osx32/chromium.app/Contents/MacOS/chromebrowser' } } }
[0-0] 2019-05-19T22:53:05.394Z INFO webdriver: Retrying 3/3
[0-0] 2019-05-19T22:53:05.394Z INFO webdriver: [POST] http://127.0.0.1:9515/session
[0-0] 2019-05-19T22:53:05.395Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', chromeOptions: [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      chromeOptions:
       { binary:
          '../../desktop/sdk/osx32/chromium.app/Contents/MacOS/chromebrowser' } } }

Stderr:
[0-0] 2019-05-19T22:53:05.358Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-chromedriver-service".
Error: Cannot find module 'chromedriver'
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
     at Module.require (internal/modules/cjs/loader.js:636:17)
     at require (internal/modules/cjs/helpers.js:20:18)
     at Object.<anonymous> (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/wdio-chromedriver-service/build/launcher.js:10:44)
     at Module._compile (internal/modules/cjs/loader.js:688:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
     at Module.load (internal/modules/cjs/loader.js:598:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
     at safeRequire (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/utils/build/initialisePlugin.js:19:13)
     at initialisePlugin (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/utils/build/initialisePlugin.js:56:18)
     at initialiseServices (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/utils/build/initialiseServices.js:64:53)
     at Runner.run (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/runner/build/index.js:88:35)
     at process.on.m (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/local-runner/build/run.js:37:20)
     at process.emit (events.js:187:15)
     at emit (internal/child_process.js:812:12)
     at process._tickCallback (internal/process/next_tick.js:63:19)
[0-0] 2019-05-19T22:53:05.392Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:9515
[0-0] 2019-05-19T22:53:05.393Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:9515
[0-0] 2019-05-19T22:53:05.394Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:9515
[0-0] 2019-05-19T22:53:05.395Z ERROR webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:9515
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
[0-0] 2019-05-19T22:53:05.395Z ERROR @wdio/runner: Error: connect ECONNREFUSED 127.0.0.1:9515
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
[0-0] 2019-05-19T22:53:05.396Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
     at Runner.run (/Users/tester/go/src/github.com/acme/webapps/app1/integration/webdriverio/node_modules/@wdio/runner/build/index.js:91:74)
     at process._tickCallback (internal/process/next_tick.js:68:7)

Worker Error:
Error: connect ECONNREFUSED 127.0.0.1:9515
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)

Test Suites:	 0 passed, 1 failed, 1 total (100% completed)
Time:		 🕔  0.28s

error Command failed with exit code 1.
```

Thank you very much!

**Comment by christian-bromann** [comment]
> And please let me know if the log is insufficient and does not give you everything you may need to help me.

Please see [install instructions](https://github.com/atti187/wdio-chromedriver-service#installation), you need to install chromedriver too via:

```sh
$ npm install chromedriver --save-dev
```

> I read the other issues to try to find the answer. Particularly notable is #11. It was a surprise to hear @christian-bromann not imagine a reason to use a specific older version of software as opposed to the latest and current version. Maybe he is only thinking about things in the realm of being "out in front" of the latest browser changes and not the creation of test cases for legacy code.

Not sure to which of my comment you are referring to but imo there is not much reason to test against an older version of Chrome as the browser updates quite regularly and updates happen automatically. But sure, every use case is different and there is nothing wrong doing that if your requirements say so.

**Comment by duderonomy** [comment]
Thank you for your input Christian. I appreciate your great work. I am testing legacy internal apps on 32 bit chromium browser. Based on my attempts I discover modern chromedriver binaries would not interoperate with the 32-bit run-time world in which I test.  

It would be convenient and intuitive if we could specify the filepath of a particular chromedriver binary in the wdio.conf.js. 

The wdio-chromedriver service is a great abstraction point. 

wdio-chromedriver service has facility for chromeDriverArgs and chromeDriverLogs. 
Does it have somewhere, `chromeDriverBinary`?
If not, that seems a reasonable _knob_ to bring to level of the wdio.conf.

Thanks for your guidance, Christian. You are doing amazing things with webdriverio.

**Comment by duderonomy** [comment]
I am beginning to see some "usability" issues surrounding these packages. 
I am happy to determine where they go awry and fix them... 
Can I run the node-chromedriver installer and set breakpoints on a cloned copy of it in my filesystem?

The node-chromedriver package may have the usability problem. 
Apparently, one cannot install node-chromedriver and then configure it afterwards (and before run-time) to use a specific chromedriver binary. 

Once installed, node-chromedriver appears to lock you into the chromedriver that was specified at install time. At least that is what I think at this point. 

When I try to specify CHROMEDRIVER_FILEPATH at install time I do not get the result I expected.

**Comment by atti187** [comment]
Hi, I'm guessing here, but what if you install a specific version of https://www.npmjs.com/package/chromedriver?activeTab=versions which is pinned to the version of Chrome you want to use for your tests, i.e. `npm install chromedriver@2.22.2`? 

Also, according to http://chromedriver.chromium.org/capabilities you should be able to specify the exact binary with `chromeOptions.binary`-option.

Either way, Chrome 32bit for Mac seems to have been dropped in 2014 according to https://gsuiteupdates.googleblog.com/2014/09/google-chrome-64-bit-for-mac-and-windows.html, and you cannot expect new tools to support these things. Maybe Browserstack has support for your os/version of Chrome? If so, use https://webdriver.io/docs/browserstack-service.html.

**Comment by duderonomy** [comment]
I appreciate that ideas. Very informative. 

I prefer not to use the older topology such as selenium when the chromedriver itself speaks the same "language" or wire protocol as it seems to be called.

A quick solution that works is to use the default installation of node-chromedriver and hack in your favorite chromedriver:

Copy the chromedriver one wants to use, to the filepath: `./node_modules/chromedriver/lib/chromedriver/chromedriver`

The interoperability between packages [webdriverio, wdio-chromedriver-service, node-chromedriver] appears to work. But it is unfortunate that the package, node-chromedriver, on which wdio-chromedriver-service depends, appears to have a broken installer when trying to use the custom binary feature (FWICT).

**Comment by duderonomy** [comment]
@atti187 Your service is very useful. Thanks for writing it.
