### ISSUE TITLE
chromeOptions unrecognized

### ISSUE THREAD

**Issue by senovsky** [atti187/wdio-chromedriver-service#25]
Hi, the chromedriver works correctly, but only without chromeOptions. I'm using the same structure like [here](https://github.com/atti187/wdio-chromedriver-service/issues/4#issue-241998043) (without `--remote-debugging-port`, `binary` and `port: '9515'`).
Chrome version 75.0.3770.142. Following error pops up:
```
Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[0-0] RUNNING in chrome - C:\Users\something\e2e\features\2-Employees\1-SmokeTest.feature
[0-0] 2019-07-29T13:43:11.982Z ERROR webdriver: Request failed due to invalid argument: invalid argument: unrecognized capability: chromeOptions
    at getErrorFromResponseBody (C:\Users\something\e2e\node_modules\webdriver\build\utils.js:371:10)
    at Request._callback (C:\Users\something\e2e\node_modules\webdriver\build\request.js:120:64)
    at Request.self.callback (C:\Users\something\e2e\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Users\something\e2e\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Users\something\e2e\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
0-0 worker error { name: 'invalid argument',
  message: 'invalid argument: unrecognized capability: chromeOptions',
  stack:
   'invalid argument: invalid argument: unrecognized capability: chromeOptions\n    at getErrorFromResponseBody (C:\\Users\\senovsky\\gitlab\\hakkastack\\e2e\\node_modules\\webdriver\\build\\utils.js:371:10)\n    at Request._callback (C:\\Users\\senovsky\\gitlab\\hakkastack\\e2e\\node_modules\\webdriver\\build\\request.js:120:64)\n    at Request.self.callback (C:\\Users\\senovsky\\gitlab\\hakkastack\\e2e\\node_modules\\request\\request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.<anonymous> (C:\\Users\\senovsky\\gitlab\\hakkastack\\e2e\\node_modules\\request\\request.js:1161:10)\n   
 at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at IncomingMessage.<anonymous> (C:\\Users\\senovsky\\gitlab\\hakkastack\\e2e\\node_modules\\request\\request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)' }
[0-0] 2019-07-29T13:43:11.985Z ERROR @wdio/runner: invalid argument: invalid argument: unrecognized capability: chromeOptions
    at getErrorFromResponseBody (C:\Users\something\e2e\node_modules\webdriver\build\utils.js:371:10)
    at Request._callback (C:\Users\something\e2e\node_modules\webdriver\build\request.js:120:64)
    at Request.self.callback (C:\Users\something\e2e\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Users\something\e2e\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Users\something\e2e\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
2019-07-29T13:43:11.986Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (C:\Users\something\e2e\node_modules\@wdio\runner\build\index.js:91:74)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[0-0] FAILED in chrome - C:\Users\something\e2e\features\2-Employees\1-SmokeTest.feature
```

**Comment by crhoads1024** [comment]
I ran into this same error after upgrading to v5 WDIO.
Try renaming
chromeOptions to goog:chromeOptions

My browser and capabilities section of the wdio.conf.js file looks like the following:
browserName: 'chrome',
        'goog:chromeOptions': {
            // uncomment the 'args' line below to support headless execution
            // args: ['--headless',  '--window-size=1024,768'],
            // Linux path:
            binary: binPath,
            w3c: true
        },

See if these capabilities help.

**Comment by senovsky** [comment]
Great, now it works, thanks :-)
